services:
  grafana:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: ''
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
  prometheus:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: ''
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
  node_exporter:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: ''
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
