services:
  traefik-01:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: ''
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
  socket-proxy:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: ''
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
