services:
  bookstack-server:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: ''
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
  bookstack-mariadb:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: ''
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
