#!/bin/bash
set -uo pipefail
LOG=/var/log/synology_weekly_backup.log
DEST=/mnt/remotes/synology_backup_point
APPDATA_DEST="$DEST/docker-data/appdata"
KEEP_APPDATA=4
WARN_PCT=85
NOTIFY=/usr/local/emhttp/plugins/dynamix/scripts/notify

log()   { echo "[$(date)] $*" >> "$LOG"; }
alert() { log "ERROR: $1"; "$NOTIFY" -e "Synology Backup" -d "$1" -i "alert"; }
avail() { df -B1 --output=avail "$DEST" | tail -1; }

prune_appdata() {
  ls -1d "$APPDATA_DEST"/ab_* 2>/dev/null | sort -r | tail -n +$(( $1 + 1 )) | while read -r d; do
    rm -rf -- "$d" && log "Pruned appdata archive $(basename "$d")"
  done
}

log "Starting"

if ! mountpoint -q "$DEST"; then
  alert "$DEST not mounted"
  exit 1
fi

FAILED=0

# Flash backups: keep only the newest zip locally; the Synology task keeps 26 on the NAS.
ls -t /mnt/user/unraid-usb/*.zip 2>/dev/null | tail -n +2 | xargs -r rm -f

rsync -ah --stats \
  /mnt/user/backups-family \
  /mnt/user/backups-friends \
  /mnt/user/personal \
  /mnt/user/unraid-usb \
  /mnt/user/vms \
  /mnt/user/editing \
  "$DEST/" --log-file="$LOG" || { alert "rsync of shares failed (exit $?)"; FAILED=1; }

# Immich library. thumbs/ and encoded-video/ are regenerated by Immich, so they are skipped.
mkdir -p "$DEST/docker-data/immich"
rsync -ah --stats \
  --exclude='/thumbs/' --exclude='/encoded-video/' \
  /mnt/user/docker-data/immich/ "$DEST/docker-data/immich/" \
  --log-file="$LOG" || { alert "rsync of Immich failed (exit $?)"; FAILED=1; }

rsync -ah --stats /mnt/user/docker-data/paperless-ngx "$DEST/docker-data/" \
  --log-file="$LOG" || { alert "rsync of Paperless failed (exit $?)"; FAILED=1; }

# Newest appdata archive, at least 60 min old so a backup still being written is never copied.
mkdir -p "$APPDATA_DEST"
SRC=$(find /mnt/user/docker-data -maxdepth 1 -type d -name 'ab_*' -mmin +60 | sort | tail -1)
if [ -z "$SRC" ]; then
  alert "No appdata archive found in /mnt/user/docker-data"
  FAILED=1
else
  NAME=$(basename "$SRC")
  if [ -d "$APPDATA_DEST/$NAME" ]; then
    log "Appdata archive $NAME already on NAS"
  else
    need=$(du -sb "$SRC" | cut -f1)
    need=$(( need + need / 10 ))
    if [ "$(avail)" -lt "$need" ]; then
      log "Low space on NAS, pruning to $(( KEEP_APPDATA - 1 )) appdata archives first"
      prune_appdata $(( KEEP_APPDATA - 1 ))
    fi
    if [ "$(avail)" -lt "$need" ]; then
      alert "Not enough space on NAS for appdata archive $NAME"
      FAILED=1
    elif rsync -ah --stats "$SRC/" "$APPDATA_DEST/.partial-$NAME/" --log-file="$LOG" \
         && mv "$APPDATA_DEST/.partial-$NAME" "$APPDATA_DEST/$NAME"; then
      prune_appdata "$KEEP_APPDATA"
    else
      alert "Copy of appdata archive $NAME failed"
      FAILED=1
    fi
  fi
fi

pct=$(df --output=pcent "$DEST" | tail -1 | tr -dc '0-9')
if [ "$pct" -ge "$WARN_PCT" ]; then
  "$NOTIFY" -e "Synology Backup" -d "NAS is ${pct}% full" -i "warning"
fi

[ "$FAILED" -eq 0 ] || exit 1
log "Done (NAS ${pct}% used)"
"$NOTIFY" -e "Synology Backup" -d "Completed successfully (NAS ${pct}% used)" -i "normal"
